### ISSUE TITLE
Don't panic on group segment elements

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry/dns-release#18]
Would it be possible to not make bosh-dns panic & crash upon encountering a dns request that's not of "valid" format? Maybe only log an error?
https://github.com/cloudfoundry/bosh-dns-release/blob/2a131cb28703cf0d553e9385ed98022367ac971d/src/bosh-dns/dns/server/criteria/segment.go#L48

We're currently experimenting with incorporating bosh-dns into our dns infrastructure, but with that panic it would be possible for an app/user to continually crash the bosh-dns by sending requests like "foo.bar.bosh".

**Comment by cppforlife** [comment]
nice find, was not intentional. we are going to figure out how to make sure we dont end up with cases like that again. fix will be out shortly (ill update here).

**Comment by cppforlife** [comment]
https://github.com/cloudfoundry/bosh-dns-release/releases/tag/v0.1.0 fixes the panic. more details on additional releases are there as well. thanks.
