### ISSUE TITLE
"*.the_deployment_name.bosh" should not match all VMs in all deployments

### ISSUE THREAD

**Issue by jessehu** [cloudfoundry/dns-release#20]
Hello, I'd like to use bosh-dns to resolve a hostname to IPs of all VMs within a deployment, but the following aliases matches to all VMs in all deployments.  

cat /var/vcap/jobs/my-aliases/dns/aliases.json
{"a.my.local":["*.service1-2e1a321358b8d3507a45.bosh"]}

nslookup a.my.local
Server:		169.254.0.2
Address:	169.254.0.2#53

Name:	a.my.local
Address: 30.0.0.12
Name:	a.my.local
Address: 30.0.0.14

cat /var/vcap/instance/dns/records.json
{"records":[["30.0.0.12","c6bc7173-3143-424c-9e6f-a404f624fbcc.service1.deployment-network.service1-2e1a321358b8d3507a45.bosh"],["30.0.0.14","5708c0e8-fa04-4290-b798-93d18a080891.harbor-app.deployment-network.service2-e3831e72d40367bb3794.bosh"]],"version":32,"record_keys":["id","num_id","instance_group","group_ids","az","az_id","network","network_id","deployment","ip","domain","agent_id","instance_index"],"record_infos":[["c6bc7173-3143-424c-9e6f-a404f624fbcc","25","service1",["15"],"az-1","1","deployment-network","1","service1-2e1a321358b8d3507a45","30.0.0.12","bosh","2ac18ad8-7d1f-4fdc-8bef-89e320133333",0],["5708c0e8-fa04-4290-b798-93d18a080891","35","myapp",["19"],"az-1","1","deployment-network","1","service2-e3831e72d40367bb3794","30.0.0.14","bosh","d5833ea9-99e9-4c29-83b2-dde2fc86

I can use (( ..service1.deployment_name )) to get the deployment name in Tile yaml, but not sure who to get the deployment network name. Is it (( ..service1.deployment_network )) ? If so, I can specify a more specific domain like "*.job1.(( ..service1.deployment_network )).(( ..service1.deployment_name )).bosh".

**Comment by cppforlife** [comment]
@jessehu 

> I'd like to use bosh-dns to resolve a hostname to IPs of all VMs within a deployment

we currently do not support such filtering. could you describe your use case?

**Comment by jessehu** [comment]
hi @cppforlife , I can use '*.instance_group_name.network_name.deployment_name.bosh' to match all IPs of VMs in that group. Here I want to report the bug that "*.depoyment-1_name.bosh" matches all VMs in all deployments, which is not expected.

**Comment by cppforlife** [comment]
> I can use '.instance_group_name.network_name.deployment_name.bosh' to match all IPs of VMs in that group. Here I want to report the bug that ".depoyment-1_name.bosh" matches all VMs in all deployments, which is not expected.

that doesnt really describe why you need this feature. any more info?

**Comment by jessehu** [comment]
@cppforlife I don't need this feature. Actually this is a bug : ".depoyment-1_name.bosh" matches all VMs in all deployments, which is not expected".

**Comment by cppforlife** [comment]
@jessehu oh im sorry, it appears i misread. will take a look on tue.

**Comment by aashah** [comment]
@jessehu You're instinct is correct to provide more information to the filter. The problem you're facing is the distinction bosh-dns makes between a long-query and short-query.

Short queries take the rough form: `{query}.{group-query}.{domain}`, for example: `q-s0.q-g7.bosh.`. When the group query does not match the correct format, we omit it from the filtering chain effectively making it `q-s0.*.bosh`. In this case, the deployment name is not a valid "group query". You can test this theory out by substituting the group-query with random letters: `dig q-s0.askhfjahfajshfja.bosh`

Gonna close this out as it stands.
