### ISSUE TITLE
bosh-dns can not match the instance name having upper case letters in aliases.json

### ISSUE THREAD

**Issue by jessehu** [cloudfoundry/dns-release#22]
e.g. I have a json file /var/vcap/jobs/myjob-aliases/dns/aliases.json
{"myapp.lab.local":["*.myapp.myNetwork.deployment-name-abcd1234.bosh"]}

'myNetwork' is the name of deployment network created in Ops Manager.

The /etc/hosts contains the following entry:
10.0.1.3 <guid>.myapp.mynetwork.deployment-name-abcd1234.bosh

mynetwork was transformed from the network name 'myNetwork' by bosh-dns.

As a result, bosh-dns can not match "*.myapp.myNetwork.deployment-name-abcd1234.bosh" to <guid>.myapp.mynetwork.deployment-name-abcd1234.bosh.

The name of network name in Ops Manager Director can contain letters, number and '-'. The deployment name (generated from the tile name) can contain letters, number, underscore and '-'. So when if using upper case letters in the network name or having '_' in the tile name, and the job which populates aliases.json do not handle the upper case letters or underscore, the issue occurs.

Better to let bosh-dns do an ignore case regex match when matching the instance name.  Thanks.

**Comment by cppforlife** [comment]
@jessehu director/bosh-dns decided to follow stricter conventions. we convert names to lowercase, underscores -> dashes, everything else stripped.

here is an example of a release that uses that to fudge custom provided aliases: https://github.com/cloudfoundry/bosh-dns-aliases-release/blob/master/jobs/bosh-dns-aliases/templates/aliases.json.erb

**Comment by dpb587-pivotal** [comment]
@cppforlife should we be `strings.ToLower`'ing the client DNS names we receive?

**Comment by jessehu** [comment]
Thanks @cppforlife. I have the same request as @dpb587-pivotal. As a result, the aliaes.json in other jobs using bosh-dns do not need to do the transformation in https://github.com/cloudfoundry/bosh-dns-aliases-release/blob/master/jobs/bosh-dns-aliases/templates/aliases.json.erb
