### ISSUE TITLE
bosh-dns can't resolve dns records with instance index number although director.local_dns.include_index is enabled

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/dns-release#25]
@cppforlife 

Our environments rely on instance index based DNS records, so I enabled local_dns.include_index property in the Director job. 
```
    director:
      local_dns:
        enabled: true
        include_index: true
```
But the instance index based DNS records like `0.nats.default.gubin-cf-new.bosh` can't be resolved by bosh-dns on the vm where bosh-dns job is deployed.
```
# nslookup 0.nats.default.gubin-cf-new.bosh
Server:		169.254.0.2
Address:	169.254.0.2#53

*** Can't find 0.nats.default.gubin-cf-new.bosh: No answer
```
But it can resolve dns records with instance ID:
```
# nslookup fdee12da-da5c-4254-8768-1ef188918098.nats.default.gubin-cf-new.bosh
Server:		169.254.0.2
Address:	169.254.0.2#53

Name:	fdee12da-da5c-4254-8768-1ef188918098.nats.default.gubin-cf-new.bosh
Address: 159.122.235.244
```
I checked `/var/vcap/instance/dns/records.json` and found the instance index based DNS records like `0.nats.default.gubin-cf-new.bosh` are only propagated in the `"records"` section
```
  "records": [
    [
      "159.122.235.244",
      "fdee12da-da5c-4254-8768-1ef188918098.nats.default.gubin-cf-new.bosh"
    ],
    [
      "159.122.235.244",
      "0.nats.default.gubin-cf-new.bosh"
    ],
...
```
But bosh-dns only resolves the records in `"record_infos"` section. Only dns records with instance ID like `fdee12da-da5c-4254-8768-1ef188918098.nats.default.gubin-cf-new.bosh` are propagated in the `"record_infos"` section. 

I tried to add `0.nats.default.gubin-cf-new.bosh` to `"record_infos"` section copying `fdee12da-da5c-4254-8768-1ef188918098.nats.default.gubin-cf-new.bosh`'s example with `"id"` changed to `"0"`. After that, bosh-dns can resolve `0.nats.default.gubin-cf-new.bosh`:
```
# nslookup 0.nats.default.gubin-cf-new.bosh
Server:		169.254.0.2
Address:	169.254.0.2#53

Name:	0.nats.default.gubin-cf-new.bosh
Address: 159.122.235.244
```
Would you please also propagate the  instance index based DNS records like `0.nats.default.gubin-cf-new.bosh` to `"record_infos"` section in `/var/vcap/instance/dns/records.json`? 

Also, would you please remove the records in /etc/hosts? I believe this is not needed when bosh-dns is deployed and will cause confusion in the case when I can ping `0.nats.default.gubin-cf-new.bosh` (record is in /etc/hosts) but indeed bosh-dns can't resolve it (nslookup fails).

Thanks.

/cc @maximilien  @mattcui

**Comment by gu-bin** [comment]
@cppforlife Any comments?

**Comment by gu-bin** [comment]
@cppforlife Any comments for this issue? Thanks.

**Comment by cppforlife** [comment]
@gu-bin looks like it's not being honored even though loaded in https://github.com/cloudfoundry/bosh-dns-release/blob/fcca7163423cac73398898d3c7f27d27e17dcd30/src/bosh-dns/dns/server/records/record_set.go#L258-L259. i think we should add this feature.

**Comment by gu-bin** [comment]
We tried on bosh-dns release 1.10.0 and the problem is still not fixed. Do you have any plan when it will be fixed? Thanks.

It can resolve dns records with instance ID:
```
nslookup 7f5b5ad5-c2b3-4650-9a0e-4ce3e2775fae.uaadb.default.stage0.microbosh
Server:		169.254.0.2
Address:	169.254.0.2#53

Name:	7f5b5ad5-c2b3-4650-9a0e-4ce3e2775fae.uaadb.default.stage0.microbosh
Address: 159.1.2.3
```

But can't resolve dns records with instance index:
```
nslookup 1.uaadb.default.stage0.microbosh
Server:		169.254.0.2
Address:	169.254.0.2#53

*** Can't find 1.uaadb.default.stage0.microbosh: No answer
```

**Comment by dpb587-pivotal** [comment]
@gu-bin we have not looked into this and since indices are not recommended (the UUIDs are preferred), we're not planning on working on this. If you are interested in this functionality, feel free to look into it yourself and submitting a pull request. If it's a small enough set of changes, we can likely merge and support it.

**Comment by andrew-edgar** [comment]
is there a way then to look up all the instances of an instance_group using a "dig" so for example, I want to know all the *.uaadb.default.stage.bosh?  I know there are 3 instances but I don't know the GUIDs so how can I look them up with the GUID if I don't know them?

**Comment by dpb587-pivotal** [comment]
@andrew-edgar currently you'd need to consume a link and iterate over `link('uaadb').instances` if you wanted individual GUIDs. However, typically you should be addressing a link by it's general hostname, not by individual VMs. Can you explain more about the use case you're working with? We might be able to find an alternative.
