### ISSUE TITLE
Is bosh-dns possible to  cache more than 1000 entries?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/dns-release#26]
The doc says "When enabled bosh-dns will cache up to a max of 1000 recursed entries". It's not enough for our Public Production environments. Is it possible to cache more entries?

**Comment by cppforlife** [comment]
@gu-bin we can make this configurable if yall need it. we just thought that this is a good default.

**Comment by gu-bin** [comment]
@cppforlife Yes, please make it configurable. Thanks.

**Comment by aashah** [comment]
This is unfortunately a value outside our configuration, found in the underlying dns library we use - https://github.com/coredns/coredns/blob/6910c9a116d55b7910975bd4d153b7fe77822c8b/plugin/cache/cache.go#L241

While it is technically possible to modify this value, it would be at the risk of diverging from their internal implementation of the Cache object.

Closing this issue.
