### ISSUE TITLE
The DNS record does not refresh inside the app container

### ISSUE THREAD

**Issue by David-VMware** [cloudfoundry/dns-release#27]
The TTL is set to zero. However the DNS record does not refresh inside the app container but this gets refreshed outside.

Here is an example. You can see the the DNS record is still old after 5 seconds.
![not_refresh_more_than_5_seconds](https://user-images.githubusercontent.com/17395452/38286464-1bedc6e8-37f8-11e8-9580-6d6ab02bd446.PNG)

However the DNS record gets refreshed out of the app container immediately.
![refresh_out_of_the_app_container](https://user-images.githubusercontent.com/17395452/38286470-22b9e63c-37f8-11e8-9592-60e126a42589.PNG)

It is still old after 20 minutes.
![refresh_out_after_20_minutes](https://user-images.githubusercontent.com/17395452/38286466-1ff0bebc-37f8-11e8-9d58-7d42ecfce6be.PNG)

I would like to share some hint that from my test experience, it seems the bosh-dns remember the `TTL` until it is restarted by `monit restart bosh-dns`.  If I restarted the bosh-dns, then the bosh-dns seems to pick up the new `TTL`, which is `0` and then the app will get the refreshed DNS record inside the container.

Here is the version number
`ubuntu@ops-manager:~$ bosh -e env3 releases`
`Using environment '192.168.111.67' as user 'director' (bosh.*.read, openid, bosh.*.admin, bosh.read, bosh.admin)`
`Name                           Version         Commit Hash`
`backup-and-restore-sdk         1.2.1*          7dae1a0`
`binary-offline-buildpack       1.0.15*         60e6eb9`
`bosh-dns                       0.1.0*          7f4c56a`
`bosh-dns-aliases               0.0.1*          a6b4e38`

**Comment by dpb587-pivotal** [comment]
@David-Pivotal your hint makes it sound like you changed the TTL from something and lowered it to 0. Is that correct?

When a TTL is more than 0, the result will be cached. So, even if the TTL or IP is changed after... it may take the original TTL duration (or longer) before DNS servers will refresh its cache and return new information.

**Comment by David-VMware** [comment]
@dpb587-pivotal Thanks for your comments.

It is correct that the TTL is changed from `604800` to `0`.

Is it by design that bosh-dns will cache the result when a TTL is more than 0. If so, we shall suggest customer to use a reasonable TTL in DNS server side, right?

**Comment by cppforlife** [comment]
nice catch @dpb587-pivotal 

> It is correct that the TTL is changed from 604800 to 0.

yeah, if ttl was set to 7 days, it will be cached for 7 days. changing to 0 isnt going to change any dns servers that cached this entry for longer. we do not do active refreshes currently.

> If so, we shall suggest customer to use a reasonable TTL in DNS server side, right?

people configure ttls to variety of times depending on use cases. setting ttl to 300s is pretty common, if records change but no too often.

**Comment by David-VMware** [comment]
@cppforlife Thanks for your comments. Please feel free to close this ticket.
