### ISSUE TITLE
v0.2.0 fails to export packages

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/dns-release#28]
https://ci2.starkandwayne.com/teams/cfcommunity/pipelines/cfcr-compiled-deployment/jobs/bosh-dns-compile-release-3541/builds/2 - I'm trying to generate a compiled release of bosh-dns v0.2.0 (version used by CFCR) but it fails ... I think because its compiling a Windows package?

I did not get this issue when I first exported v1.4.0 so perhaps the issue is fixed; but I'd like a version of 0.2.X that matches to what cfcr.yml expects, please?

**Comment by cppforlife** [comment]
@drnic we probably put in a windows hack in later versions. 0.2.x is super old, they should bump or just rely on runtime config adding bosh-dns (preferred).

**Comment by drnic** [comment]
"rely on runtime config" - that still uses this boshrelease, just injected it via runtime-config rather than an addon within the deployment manifest?

Does cf-deployment currently assume bosh-dns is always enabled for its cf-deployment.yml?

**Comment by drnic** [comment]
@cloudoundry-incubator/kubo-deployment are you bumping to latest bosh-dns release soon?

**Comment by cppforlife** [comment]
> "rely on runtime config" - that still uses this boshrelease, just injected it via runtime-config rather than an addon within the deployment manifest?

https://github.com/cloudfoundry/bosh-deployment/blob/master/runtime-configs/dns.yml

> Does cf-deployment currently assume bosh-dns is always enabled for its cf-deployment.yml?

dont think so, but one could exclude certain deployments in runtime configs.

**Comment by cppforlife** [comment]
@drnic no plans to fix this for 0.2.x. closing.
