### ISSUE TITLE
Only the 1st entry specified in recursors can work

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/dns-release#3]
Seems only the 1st entry specified in [recursors](https://bosh.io/jobs/bosh-dns?source=github.com/cloudfoundry/dns-release&version=0.0.8#p=recursors) can work, but DNS resolution requests can't be forwarded to the subsequent entries. For example, below is my config.json:

```json
{"address":"169.254.0.2","port":53,"recursors":["127.0.0.1","8.8.8.8"],"records_file":"/var/vcap/instance/dns/records.json","alias_files_glob":"/var/vcap/jobs/*/dns/aliases.json","upcheck_domains":["upcheck.bosh-dns."],"recursor_timeout":"2s","health":{"enabled":false,"port":8853,"certificate_file":"config/certs/client.crt","private_key_file":"config/certs/client.key","ca_file":"config/certs/client_ca.crt","check_interval":"20s","max_tracked_queries":2000}}
```

I added 127.0.0.1 for consul dns, and 8.8.8.8. I can see all consul entries can be resolved:

```
# ping bbs.service.cf.internal
PING bbs.service.cf.internal (169.50.199.177) 56(84) bytes of data.
64 bytes from 169.50.199.177: icmp_seq=1 ttl=64 time=1.02 ms
64 bytes from 169.50.199.177: icmp_seq=2 ttl=64 time=0.379 ms
```

But I can't ping www.google.com:

```
# ping www.google.com
ping: unknown host www.google.com
```

However, if I set them in reverse, like `"recursors":["8.8.8.8","127.0.0.1"]`, then  consul entries can't be resolved, but public domains can be resolved.

I am using v0.0.8 release, and only set `169.254.0.2` in /etc/resolv.conf.

/cc @cppforlife @maximilien

**Comment by cppforlife** [comment]
@mattcui this is working as expected since recursors must be equivalent. they are not meant to be used for resolution failover, but rather for nameserver availability failover.

can you explain why do you need such setup?

**Comment by mattcui** [comment]
@cppforlife Let me give you some background and an brief introduction of existing solution we adopted, in general, we have a few (5+) dns servers needed to be used to resolve dns domains/hosts, including powerdns, consul, customer and public dns servers. Below is a sample if we define them all in resolv.conf:

```
nameserver 127.0.0.1  # consul server
nameserver 169.60.xx.xx  # power dns
nameserver xx.xx.xx.xx  # customer dns
nameserver 10.0.80.11  # SL pub dns
nameserver 10.0.80.12  # SL pub dns
nameserver 8.8.8.8
nameserver 8.8.4.4
```

but as you know, there is a known problem where only the first 3 dns server defined in resolv.conf can be used, so currently we used [unbound](http://unbound.nlnetlabs.nl/index.html) to help solve this issue, we configured unbound like below, so that unbound can try to help resolve domains/hosts starting from `local-zone`, if it can't resolve, unbound will continue to use dns servers defined in `stub-zone` to resolve and then to use `forward-zone` in order.

```
server: 
  local-zone:
  local-data:....

stub-zone:
  name: "microbosh"
  stub-addr: 169.60.xx.xx  # power dns
stub-zone:   
  name: "xxxx  "
  stub-addr: xx.xx.xx.xx  # customer dns
forward-zone:
  name: "."
  forward-addr: 10.0.80.11
  forward-addr: 10.0.80.12
  forward-addr: 8.8.8.8
  forward-addr: 8.8.4.4
```

If we move to bosh-dns, apparently, I hope bosh-dns can replace both powerdns and unbound (it could replace consul in future). I expected bosh-dns can work partially like unbound, it can help forward the request to all dns servers defined in recursors  in order if the pervious dns can't resolve. So for our case, do you think if we still have to use unbound alike service to help manage dns servers or there is a better way to get rid of unbound? Thanks.

/cc @maximilien

**Comment by cppforlife** [comment]
@mattcui sounds like we can simplify this a lot. i've added story [1] to extend bosh-dns's ability to resolve particular domains via particular recursors. would that work for your use case?

[1] https://www.pivotaltracker.com/story/show/152009455

**Comment by mattcui** [comment]
@cppforlife I think it's good, I will watch the story and have a try immediately once it's implemented in a new release build. Thank you!

**Comment by mattcui** [comment]
@cppforlife Seems the story tries to implement `stub-zone` alike functionality, do you think if it can also support the functionality as `forward-zone` does? For example, I may need to specify 2 internal SL DNS servers (10.0.80.11, 10.0.80.12) prior to Google DNS server. Also, I think there should support to specify * for `domain:`, right? Thanks.

**Comment by cppforlife** [comment]
> Also, I think there should support to specify * for domain:, right? Thanks.

we support `.` i believe.

> For example, I may need to specify 2 internal SL DNS servers (10.0.80.11, 10.0.80.12) prior to Google DNS server.

what is the behaviour there? what do 10.0.x servers provide that 8.8.8.8 doesnt?

**Comment by mattcui** [comment]
@cppforlife Actually, I am not very sure what is the difference between SL DNS and Google DNS, but currently, we set both in resolver file, maybe when public networking is not stable, the private SL DNS still can function as failover.

**Comment by maximilien** [comment]
Is there a resolution for this?

**Comment by cppforlife** [comment]
@maximilien @mattcui 

> Is there a resolution for this?

not sure, are we ok to proceed with current configuration?

**Comment by mattcui** [comment]
@cppforlife @maximilien Haven't got chance to re-test, we expect it should replace both powerdns and consul eventually, currently, we haven't used `diego-locket` release to manage locks in our test and production environments, we will re-test `bosh-dns` once we can use `diego-locket` to replace the lock function of consul.

**Comment by cppforlife** [comment]
@mattcui did you have a chance to check up?

**Comment by mattcui** [comment]
I learned that we can specify to use different dns server to resolve names from different domains through handler. Closing this issue.
