### ISSUE TITLE
[Feature] As an operator, I want to configure the log-level for bosh-dns, such that a busy service doesn't spam my log service

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/dns-release#35]
It seems that the log level is [hardcoded to `debug`](https://github.com/cloudfoundry/bosh-dns-release/blob/master/src/bosh-dns/dns/main.go#L61), which means that every dns request is logged. In a busy environment this can mean a huge load of logs with little to no benefit.

Could we introduce a log level that logs errors of all sorts, but doesn't care about successful dns requests? Wdyt?

**Comment by christarazi** [comment]
Fixed in dd5afa3782273d54b46d1d2dead9fbe3bfb83fe4.

Please let us know if this works for you.

**Comment by voelzmo** [comment]
Awsome, thanks @christarazi!
