### ISSUE TITLE
DNS Server Cache Snooping Remote Information Disclosure

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/dns-release#41]
We have a special requirement to expose one bosh dns server for access by some other components, those components are not managed by BOSH, so there can't deploy bosh dns, but they need to resolve cf/bosh domain name. But if we expose bosh dns service, we got security alert ["DNS Server Cache Snooping Remote Information Disclosure"](https://www.tenable.com/plugins/nessus/12217). From [this stackoverflow post](https://unix.stackexchange.com/questions/456578/dnsmasq-server-cache-snooping-remote-information-disclosure/456585), seems it can be solved by

`Always return a SERVFAIL answer to DNS queries without the recursion desired bit set, UNLESS acting as an authoritative DNS server. This avoids a potential route to cache snooping.`

Is it possible for bosh dns to apply the similar solution to avoid this disclosure? Thanks.

**Comment by dpb587-pivotal** [comment]
This seems like a reasonable suggestion. From my perspective, this seems like a low priority given the following:

 * I don't think we currently look at the "recursion desired" bit at all before we recurse (could probably consider that a bug). This means there is currently no difference between requests which have the bit and don't. Assuming you are okay with the server recursing at all, there's no additional risk.
 * snooping data can still be discovered via recursive queries, and I expect you'll still have recursive queries enabled in your environment. There aren't really practical options to avoid this.
 * bosh-dns should be an internal service and not publicly exposed. This helps reduce (but not eliminate) the threat of snooping and malicious intent.

If you want to work on a pull request which correctly respects the recursion desired bit *and* can respond with an error which correctly respects which hosts and domains bosh-dns considers itself authoritative for (keep in mind there may be several custom handlers/domains registered), feel free to look into it and work on a pull request. Then we can take a closer look.

I would recommend researching further if `SERVFAIL` is the best response in this situation and if there are better practices. I think there may be a softer error that can be returned and let the client know that recursion is available for them to try again.

**Comment by gu-bin** [comment]
@dpb587-pivotal 
PR https://github.com/cloudfoundry/bosh-dns-release/pull/42 has been submitted. Would you please review? Thanks.

**Comment by gu-bin** [comment]
@luan When will you publish a new release for bosh-dns-release which contains the fix? Thanks.

**Comment by jaresty** [comment]
We're working on releasing a new feature so this should be released shortly after this release marker [here](https://www.pivotaltracker.com/story/show/161593525).

**Comment by aashah** [comment]
no-op closing this as a bosh-dns-release has been cut since.
