### ISSUE TITLE
Will you remove bosh dns entries in /etc/hosts?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/dns-release#46]
Currently there are some bosh dns entries in /etc/hosts when bosh-dns is deployed. Some are duplicated to records.json (like `fdee12da-da5c-4254-8768-1ef188918098.nats.default.gubin-cf-new.bosh` with UUID), some are not (like 0.nats.default.gubin-cf-new.bosh with index). 

Will you keep the bosh dns entries in /etc/hosts forever or remove them in the future? If you will remove, when will it happen? Thanks.

**Comment by luan** [comment]
@gu-bin we have no current plans that I know of to remove those. Generally we expect that `records.json` and the `bosh-dns` will provide more comprehensive functionality.

CC @mgadiya
