### ISSUE TITLE
healthcheck fails on diego-api node after a time causing issues

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/dns-release#47]
In our large deployment (700Cells) the bosh-dns-healthcheck in the diego-api ends up with many of the following errors ...

```
[healthServer] 2019/05/02 06:38:56 ERROR - Failed to read healthcheck data . error: open /var/vcap/instance/health.json: too many open files
[healthServer] 2019/05/02 06:38:56 ERROR - Failed to read healthcheck data . error: open /var/vcap/instance/health.json: too many open files
[healthServer] 2019/05/02 06:38:56 ERROR - Failed to read healthcheck data . error: open /var/vcap/instance/health.json: too many open files
[healthServer] 2019/05/02 06:38:56 ERROR - Failed to read healthcheck data . error: open /var/vcap/instance/health.json: too many open files
```

This has the impact of causing the BBS convergence time to go through the roof as it looks like all the cells are having issues connecting and checking the health.

When this occurs we simply monit restart the bosh-dns-healthcheck and things recover.

But it needs to be investigated 

1) Why do we run out of file handles in this?
2) Why does this cause issues in the diego-api?

Can you please investigate this to know how this is supposed to work and how we could run out of FDs.

**Comment by christarazi** [comment]
@andrew-edgar Have you seen this recently? If so, please feel free to re-open.
