### ISSUE TITLE
bosh-dns stops processing requests when VM/CPU is throttled by IaaS

### ISSUE THREAD

**Issue by ionphractal** [cloudfoundry/dns-release#53]
After upgrading one of our CF environments on AWS to use bosh-dns v1.15.0, we got occasional "Failed communicating with UAA: The UAA was unavailable" error messages in Cloud Controller logs, even though one could nc/curl all of the UAAs via IP while this error was present. It turned out that on the affected node, bosh-dns was not responding to requests anymore.

In netstat one could see the Recv-Q rising:
```
udp   213504      0 169.254.0.2:53          0.0.0.0:*                           1000       33980       7705/bosh-dns
udp   190464      0 169.254.0.2:53          0.0.0.0:*                           1000       33977       7705/bosh-dns
```

As it turned out, the performance issue https://github.com/cloudfoundry/bosh-dns-release/issues/52 tipped over CPU usage / credit drainage on the primary node API node. When the credit balance reached 0 and the VM was throttled by AWS, bosh-dns first got errors like
```
DEBUG - State for IP <172.17.x.x> changed from running to unknown
```
in `bosh_dns.stdout.log` and after a while, the said error in the CC happened. There is no other error message in the log. It also did not recover once CPU credits went back to normal but the bosh-dns process had to be restarted.

I could not replicate this when there was no throttling set (e.g. by using cpuburn with a higher nice value than bosh-dns) but the issue occurred when the VM was throttled (also happened to me on vSphere when deliberately limiting the CPU). I know this is rather an IaaS specific issue and you can basically mitigate it by throwing around money (unlimited / scaling instances). But I don't think software is supposed to stop working completely when resources are throttled. Yet I at least wanted to make you aware of this.

**Comment by mfine30** [comment]
Thanks for letting us know @ionphractal. Your description sounds very similar to other reports of performance issues we received with v1.15.0 of bosh-dns. This should be addressed in [v1.16.0](https://github.com/cloudfoundry/bosh-dns-release/releases/tag/v1.16.0). 

Given it sounds like this is fixed in v1.16.0 I'm going to close this for now. If you are still seeing this on v1.16.0 feel free to re-open this issue and let us know.
