### ISSUE TITLE
BOSH DNS fails to deploy on Windows 2016 (1709)

### ISSUE THREAD

**Issue by sesmith177** [cloudfoundry/dns-release#6]
On the most recent version of windows 2016, the DNS Cache service is unstoppable:

```
C:\Windows\system32>sc query dnscache

SERVICE_NAME: dnscache
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

This means that the line in the prestart script that stops the service:

https://github.com/cloudfoundry/bosh-dns-release/blob/master/jobs/bosh-dns-windows/templates/pre-start.ps1.erb#L53

will always fail.

One potential workaround / hack would be to:
1. Edit a registry key to disable the service (https://technet.microsoft.com/en-us/library/cc959920.aspx)
2. Kill the process that is running the service (PID can be found using `(Get-WmiObject -Class win32_service -filter "name LIKE 'dnscache'").ProcessId`)

We can't find a way to change the ttl on the cache without restarting the service or restarting the computer, neither of which are possible. Changing the ttl on the stemcell directly is not really an option as that would break consul

**Comment by sunjayBhatia** [comment]
Updated context from @sesmith177  in Slack:

it looks like setting `HKLM\SYSTEM\CurrentControlSet\Services\Dnscache\Paramaters\MaxCacheTtl` will work without restarting the service

i tried it and it appears to work
 
here's a msdn link to that effect https://technet.microsoft.com/en-us/library/cc959926.aspx
 
actaully, i think that link is wrong (or out of date) -- it says that editing the registry doesn't take affect immediately, even though it works when i tried it

**Comment by ships** [comment]
hey, @sunjayBhatia , i was reviewing and merging your PR with @pivotal-dale-wick and we found that it causes the test assertions in https://github.com/cloudfoundry/bosh-dns-release/blob/master/src/bosh-dns/acceptance_tests/windows/windows_test.go#L49-L66 to fail -- that test explicitly asserts that caching is disabled at system level. Would you be able to work with us to patch the test as well?

On a related note, we are testing this patch on both 2012 and 2016 stemcells, and the 2016 pre-starts are still failing. We're not confident we've set everything up right, but it may indicate that this change is not complete.

**Comment by sunjayBhatia** [comment]
@jraqula @pivotal-dale-wick we are taking a look at deploying BOSH DNS with OS caching turned on with windows2016 since the changes we made did not cover that case and that is the deployment that is failing in your CI

As far as the tests go, there are now going to be changes to the two cases:
1. OS caching turned on: ensure service is enabled/running and that the `MaxCacheTtl` parameter to the service is not set to 0/is unset so it takes the default value
2. OS caching turned off: we no longer care if the service is running since we can't turn it off, just that the `MaxCacheTtl` parameter to the service is set to 0

@aminjam and I would suggest checking the above parameter with the following powershell:
```
$RegistryPath = "HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters"
(Get-ItemProperty -Path $RegistryPath).MaxCacheTtl
```

**Comment by sunjayBhatia** [comment]
@jraqula @pivotal-dale-wick we have an updated PR here: https://github.com/cloudfoundry/bosh-dns-release/pull/12 that deploys successfully with both windows2012R2 and windows2016 with os caching on and off (and migrations back and forth between the property settings).

**Comment by dalewick** [comment]
@sunjayBhatia, https://github.com/cloudfoundry/bosh-dns-release/pull/12 was merged earlier and ran through our CI but to no avail, we are still encountering the same error with the pre-start script:

>  L Error: Action Failed get_task: Task ddaca29d-6743-4e38-5275-d9118dfbef1f result: 1 of 1 pre-start scripts failed. Failed Jobs: bosh-dns-windows.

Maybe we could pair on this tomorrow?

**Comment by sunjayBhatia** [comment]
@pivotal-dale-wick what do the error logs of the job say?

**Comment by sunjayBhatia** [comment]
@pivotal-dale-wick also, yes we are available to pair today

**Comment by dalewick** [comment]
@sunjayBhatia The full transcript is here: https://main.bosh-ci.cf-app.com/teams/main/pipelines/bosh-dns-release/jobs/test-acceptance-windows2016/builds/7

**Comment by sunjayBhatia** [comment]
@pivotal-dale-wick that output does not include the job logs from the failed pre-start

Can you paste the output of the `bosh-dns-windows` pre-start logs from `bosh logs -d bosh-dns-windows-acceptance dns-with-system-caching`

**Comment by dalewick** [comment]
pre-start.stderr.log

```
Get-NetIPAddress : No MSFT_NetIPAddress objects found with property
'IPAddress' equal to '169.254.0.2'.  Verify the value of the property and
retry.
At C:\var\vcap\jobs\bosh-dns-windows\bin\pre-start.ps1:3 char:1
+ Get-NetIPAddress -IPAddress 169.254.0.2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (169.254.0.2:String) [Get-NetIPA
   ddress], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_IPAddress,Get-NetIPA
   ddress

Remove-ItemProperty : Property MaxCacheTtl does not exist at path
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters.
At C:\var\vcap\jobs\bosh-dns-windows\bin\pre-start.ps1:34 char:3
+   Remove-ItemProperty -Path $RegistryPath -Name MaxCacheTtl
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (MaxCacheTtl:String) [Remove-It
   emProperty], PSArgumentException
    + FullyQualifiedErrorId : System.Management.Automation.PSArgumentException
   ,Microsoft.PowerShell.Commands.RemoveItemPropertyCommand
```

pre-start.stdout.log
```

Found loopback interface at InterfaceIndex 1


IPAddress         : 169.254.0.2
InterfaceIndex    : 1
InterfaceAlias    : Loopback Pseudo-Interface 1
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 32
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 169.254.0.2
InterfaceIndex    : 1
InterfaceAlias    : Loopback Pseudo-Interface 1
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 32
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Invalid
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : PersistentStore
```

**Comment by mhoran** [comment]
This is fixed in master.
